### ISSUE TITLE
Uncaught Error: Module version mismatch. Expected 43, got 14.

### ISSUE THREAD

**Issue by fentas** [atom/highlights#21]
Hi there,
I added highlights to my atom package and installed it.
> highlights@1.2.0 node_modules/highlights
├── underscore-plus@1.6.6 (underscore@1.6.0)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
└── first-mate@3.1.0 (event-kit@1.2.0, grim@1.4.1, emissary@1.3.3, oniguruma@4.2.2)

But the moment I include the package ```Highlights = require 'highlights'``` the latter error is thrown.
> ATOM_SHELL_ASAR.js:118
*Stack trace:*
Error: Module version mismatch. Expected 43, got 14.
  at Error (native)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/user/github/to-base64/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma/lib/oniguruma.js:4:17)
  at Object.<anonymous> (/home/user/github/to-base64/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma/lib/oniguruma.js:65:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/opt/atom/resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/user/github/to-base64/node_modules/highlights/node_modules/first-mate/lib/grammar.js:10:16)
  at Object.<anonymous> (/home/user/github/to-base64/node_modules/highlights/node_modules/first-mate/lib/grammar.js:342:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/opt/atom/resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/user/github/to-base64/node_modules/highlights/node_modules/first-mate/lib/grammar-registry.js:12:13)
  at Object.<anonymous> (/home/user/github/to-base64/node_modules/highlights/node_modules/first-mate/lib/grammar-registry.js:225:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/opt/atom/resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/user/github/to-base64/node_modules/highlights/node_modules/first-mate/lib/first-mate.js:4:22)
  at Object.<anonymous> (/home/user/github/to-base64/node_modules/highlights/node_modules/first-mate/lib/first-mate.js:8:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/opt/atom/resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/user/github/to-base64/node_modules/highlights/lib/highlights.js:12:21)
  at Object.<anonymous> (/home/user/github/to-base64/node_modules/highlights/lib/highlights.js:178:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/opt/atom/resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/user/github/to-base64/lib/to-base64-view-extensions.coffee:2:14)
  at Object.<anonymous> (/home/user/github/to-base64/lib/to-base64-view-extensions.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/opt/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/user/github/to-base64/lib/to-base64-view.coffee:5:1)
  at Object.<anonymous> (/home/user/github/to-base64/lib/to-base64-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/opt/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at /home/user/github/to-base64/lib/to-base64.coffee:15:23
  at module.exports.Workspace.addOpener.wrappedOpener (/opt/atom/resources/app.asar/src/workspace.js:511:18)
  at Workspace.module.exports.Workspace.openURIInPane (/opt/atom/resources/app.asar/src/workspace.js:433:22)
  at Workspace.module.exports.Workspace.open (/opt/atom/resources/app.asar/src/workspace.js:366:19)
  at atom-workspace.module.exports.activate.atom.commands.add.to-base64:view (/home/user/github/to-base64/lib/to-base64.coffee:22:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.__bind [as handleCommandEvent] (/opt/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/atom/resources/app.asar/src/command-registry.js:153:19)
  at [object Object].jQuery.fn.trigger (/opt/atom/resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:76:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/opt/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/opt/atom/resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/opt/atom/resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:149:33)
  at HTMLDocument.jQuery.event.add.handler (/opt/atom/resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/opt/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.jQuery.event.add.elemData.handle (/opt/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

Add. infos:
- nodejs: 0.12.4
- atom: 0.201.0 5/22/2015, 12:20:36 AM
- package.json: ```"highlights": "^1.2.0"```

**Comment by fentas** [comment]
Hi there,
to day atom disabled my package because I had highlights installed (not used).
-> The message was that *oniguruma* has this version mismatch and is incompatible (and so my package too).
As I can tell is *first-mate* using *oniguruma*.
I had to remove it complitly in order to get it running again.

**Comment by maxbrunsfeld** [comment]
@fentas This error occurs when a node module is compiled to work with node.js rather than atom. Did you install `highlights` using `npm install`? To fix the issue, you should run `apm rebuild` from the directory of the package that is failing to load. Let me know if this does not work for you.

**Comment by maxbrunsfeld** [comment]
Also, when you want to add a new node module as a dependency of your package, you can add it to your package's `package.json` and run `apm install` (rather than `npm install`). This will compile the module against atom, so that you don't have to rebuild it as a separate step.
